/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type LabelEntry struct {

	LabelId string `json:"labelId"`

	Name string `json:"name,omitempty"`

	Revision int32 `json:"revision,omitempty"`
}
