/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Dialogue struct {

	DialogueId string `json:"dialogueId"`

	Created int32 `json:"created"`

	Modified int32 `json:"modified"`

	Revision int32 `json:"revision"`

	Active bool `json:"active"`

	Linked bool `json:"linked"`

	Synced bool `json:"synced"`

	AmigoId string `json:"amigoId"`
}
