/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Amigo struct {

	AmigoId string `json:"amigoId"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Logo string `json:"logo,omitempty"`

	Location string `json:"location,omitempty"`

	Node string `json:"node"`

	Registry string `json:"registry,omitempty"`

	Revision int32 `json:"revision"`

	Version string `json:"version"`

	Handle string `json:"handle,omitempty"`
}
