/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type ServiceAccess struct {

	EnableShow bool `json:"enableShow,omitempty"`

	EnableIdentity bool `json:"enableIdentity,omitempty"`

	EnableProfile bool `json:"enableProfile,omitempty"`

	EnableGroup bool `json:"enableGroup,omitempty"`

	EnableShare bool `json:"enableShare,omitempty"`

	EnablePrompt bool `json:"enablePrompt,omitempty"`

	EnableService bool `json:"enableService,omitempty"`

	EnableIndex bool `json:"enableIndex,omitempty"`

	EnableUser bool `json:"enableUser,omitempty"`

	EnableAccess bool `json:"enableAccess,omitempty"`

	EnableAccount bool `json:"enableAccount,omitempty"`

	EnableConversation bool `json:"enableConversation,omitempty"`
}
