/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type ShareEntry struct {

	ShareId string `json:"shareId"`

	Revision int32 `json:"revision,omitempty"`

	Status string `json:"status"`

	AmigoId string `json:"amigoId"`

	Token string `json:"token,omitempty"`

	Updated int64 `json:"updated,omitempty"`
}
