/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Blurb struct {

	BlurbId string `json:"blurbId"`

	AmigoId string `json:"amigoId"`

	Schema string `json:"schema"`

	Data string `json:"data"`

	Revision int32 `json:"revision"`

	Created int32 `json:"created"`

	Updated int32 `json:"updated"`
}
