/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type SystemStat struct {

	Timestamp int32 `json:"timestamp"`

	Processor int32 `json:"processor"`

	Memory int64 `json:"memory"`

	Storage int64 `json:"storage"`

	Requests int64 `json:"requests"`

	Accounts int64 `json:"accounts"`
}
