/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type SubjectEntry struct {

	Subject *Subject `json:"subject"`

	Share bool `json:"share"`

	Ready bool `json:"ready"`

	Assets []SubjectAsset `json:"assets"`

	Originals []OriginalAsset `json:"originals"`

	Labels []string `json:"labels,omitempty"`
}
