/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type AlertEntry struct {

	AlertId string `json:"alertId"`

	Created int64 `json:"created"`

	Message string `json:"message,omitempty"`
}
