/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Tag struct {

	TagId string `json:"tagId"`

	AmigoId string `json:"amigoId"`

	AmigoName string `json:"amigoName,omitempty"`

	AmigoRegistry string `json:"amigoRegistry,omitempty"`

	Created int64 `json:"created"`

	Schema string `json:"schema"`

	Data string `json:"data"`
}
