/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Subject struct {

	SubjectId string `json:"subjectId"`

	Revision int32 `json:"revision"`

	Created int64 `json:"created"`

	Modified int64 `json:"modified"`

	Expires int64 `json:"expires,omitempty"`

	Schema string `json:"schema,omitempty"`

	Data string `json:"data,omitempty"`
}
