/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Topic struct {

	TopicId string `json:"topicId"`

	Revision int32 `json:"revision"`

	Blurbs []Blurb `json:"blurbs"`
}
