/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Revisions struct {

	ShowRevision int32 `json:"showRevision,omitempty"`

	IdentityRevision int32 `json:"identityRevision,omitempty"`

	ProfileRevision int32 `json:"profileRevision,omitempty"`

	GroupRevision int32 `json:"groupRevision,omitempty"`

	ShareRevision int32 `json:"shareRevision,omitempty"`

	PromptRevision int32 `json:"promptRevision,omitempty"`

	ServiceRevision int32 `json:"serviceRevision,omitempty"`

	IndexRevision int32 `json:"indexRevision,omitempty"`

	UserRevision int32 `json:"userRevision,omitempty"`

	ListingRevision int32 `json:"listingRevision,omitempty"`

	ContactRevision int32 `json:"contactRevision,omitempty"`

	ViewRevision int32 `json:"viewRevision,omitempty"`

	InsightRevision int32 `json:"insightRevision,omitempty"`

	DialogueRevision int32 `json:"dialogueRevision,omitempty"`
}
