/*
 * CoreDB API
 *
 * An interface to distributed nodes for personal storage.
 *
 * API version: 1.0.4
 * Contact: info@coredb.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package coredb

type Token struct {

	AmigoId string `json:"amigoId,omitempty"`

	Token string `json:"token"`

	Issued int64 `json:"issued,omitempty"`

	Expires int64 `json:"expires,omitempty"`
}
