version: "3"
volumes:
  coredb-asset:
  coredb-keystore:
  coredb-config:
  coredb-db:
  coredb-dev:
services:
  app:
    image: 'coredb-dev'
    restart: unless-stopped
    ports:
      - '8081:8080'
      - '222:22'
    volumes:
      - coredb-asset:/data/asset
      - coredb-keystore:/data/keystore
      - coredb-config:/data/config
      - coredb-dev:/data/dev
    environment:
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=mysqlname
      - MYSQL_HOST=db
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - coredb-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=mysqlname
    networks:
      - default

