-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 11:32:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `emigo_registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emigo_registry` (
  `emigo_id` VARCHAR(64) NOT NULL DEFAULT '',
  `name` VARCHAR(1024) NULL,
  `location` VARCHAR(1024) NULL,
  `description` VARCHAR(4096) NULL,
  `logo` TEXT(65535) NULL,
  `revision` INT NOT NULL,
  `version` VARCHAR(32) NOT NULL,
  `blocked` TINYINT NOT NULL DEFAULT 0,
  `handle` VARCHAR(128) NULL,
  `node` VARCHAR(1024) NULL,
  `registry` VARCHAR(1024) NULL,
  PRIMARY KEY (`emigo_id`),
  UNIQUE INDEX `emigo_registry_id_UNIQUE` (`emigo_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topic_registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topic_registry` (
  `topic_id` VARCHAR(64) NOT NULL DEFAULT '',
  `name` VARCHAR(1024) NULL,
  `description` VARCHAR(4096) NULL,
  `logo` TEXT(65535) NULL,
  `message` TEXT(65535) NOT NULL,
  `blocked` TINYINT NOT NULL DEFAULT 0,
  UNIQUE INDEX `uuid_UNIQUE` (`topic_id` ASC),
  PRIMARY KEY (`topic_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_registry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL DEFAULT '',
  `blocked` TINYINT NOT NULL DEFAULT 0,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emigo_registry_emigo_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `emigo_registry_id_UNIQUE` (`emigo_id` ASC),
  CONSTRAINT `servcie_emigo_registry`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo_registry` (`emigo_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emigo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL DEFAULT '',
  `account_id` INT NOT NULL,
  `prompt` TINYINT NULL,
  `accept` TINYINT NULL,
  `enabled` TINYINT NULL,
  `hidden` TINYINT NULL,
  `notes` VARCHAR(4096) NULL,
  INDEX `account_id` (`id` ASC),
  INDEX `account_idx` (`account_id` ASC),
  INDEX `emigo_emigo_registry_idx` (`emigo_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_emigo_id_UNIQUE` (`account_id`, `emigo_id`),
  UNIQUE INDEX `emigo_id_UNIQUE` (`id` ASC),
  CONSTRAINT `emigo_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emigo_emigo_registry`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo_registry` (`emigo_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `locked` TINYINT NOT NULL DEFAULT 0,
  `dirty` TINYINT NOT NULL DEFAULT 1,
  `index_revision` INT NOT NULL DEFAULT 0,
  `share_revision` INT NOT NULL DEFAULT 0,
  `prompt_revision` INT NOT NULL DEFAULT 0,
  `user_revision` INT NOT NULL DEFAULT 0,
  `identity_revision` INT NOT NULL DEFAULT 0,
  `profile_revision` INT NOT NULL DEFAULT 0,
  `catalog_revision` INT NOT NULL DEFAULT 0,
  `group_revision` INT NOT NULL DEFAULT 0,
  `contact_revision` INT NOT NULL DEFAULT 0,
  `view_revision` INT NOT NULL DEFAULT 0,
  `show_revision` INT NOT NULL DEFAULT 0,
  `service_revision` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `account_emigo_idx` (`emigo_id` ASC),
  CONSTRAINT `account_emigo`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo_registry` (`emigo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_prompt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_prompt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `prompt_id` VARCHAR(32) NOT NULL,
  `image` TEXT(65535) NULL,
  `question` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `prompt_id_UNIQUE` (`account_id`, `prompt_id`),
  INDEX `account_idx` (`account_id` ASC),
  CONSTRAINT `prompt_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prompt_id` INT NOT NULL,
  `answer_id` VARCHAR(32) NOT NULL,
  `answer` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `answer_id_UNIQUE` (`prompt_id`, `answer_id`),
  INDEX `prompt_idx` (`prompt_id` ASC),
  CONSTRAINT `account_answer_prompt`
    FOREIGN KEY (`prompt_id`)
    REFERENCES `account_prompt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` VARCHAR(64) NOT NULL DEFAULT '',
  `account_id` INT NOT NULL,
  `prompt` TINYINT NOT NULL DEFAULT 0,
  `accept` TINYINT NOT NULL DEFAULT 0,
  `hidden` TINYINT NOT NULL DEFAULT 1,
  `enabled` TINYINT NOT NULL DEFAULT 0,
  `notes` VARCHAR(4096) NULL,
  INDEX `account_id` (`id` ASC),
  INDEX `account_idx` (`account_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `topic_id_UNIQUE` (`id` ASC),
  CONSTRAINT `topic_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `topic_topic_registry`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic_registry` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `share_prompt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `share_prompt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `prompt_id` VARCHAR(32) NOT NULL,
  `emigo_id` VARCHAR(64) NOT NULL,
  `emigo_message_key` VARCHAR(4096) NOT NULL,
  `emigo_message_key_type` VARCHAR(32) NOT NULL,
  `emigo_message_signature` VARCHAR(1024) NOT NULL,
  `emigo_message_data` TEXT(65535) NOT NULL,
  `topic_id` VARCHAR(64) NULL,
  `topic_message_data` TEXT(65535) NULL,
  `prompt_token` VARCHAR(64) NOT NULL,
  `share_token` VARCHAR(64) NOT NULL,
  `fail_count` INT NULL,
  `expires` INT(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `share_prompt_account_idx` (`account_id` ASC),
  UNIQUE INDEX `prompt_token_UNIQUE` (`prompt_token` ASC),
  CONSTRAINT `confirm_request_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `share_pending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `share_pending` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `emigo` VARCHAR(64) NOT NULL,
  `emigo_message_key` VARCHAR(4096) NOT NULL,
  `emigo_message_key_type` VARCHAR(32) NOT NULL,
  `emigo_message_signature` VARCHAR(1024) NOT NULL,
  `emigo_message_data` TEXT(65535) NOT NULL,
  `topic` VARCHAR(64) NULL,
  `topic_message_data` TEXT(65535) NULL,
  `share_id` VARCHAR(32) NOT NULL,
  `emigo_id` INT NULL,
  `topic_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `share_pending_share_key` (`account_id`, `share_id`),
  INDEX `share_pending_share_idx` (`share_id` ASC),
  INDEX `share_pending_account_idx` (`account_id` ASC),
  CONSTRAINT `pending_request_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pending_request_emigo`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pending_request_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `share_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `share_connection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `emigo_id` INT NOT NULL,
  `topic_id` INT NULL,
  `share_id` VARCHAR(32) NOT NULL,
  `in_token` VARCHAR(64) NULL,
  `out_token` VARCHAR(64) NULL,
  `state` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `share_connection_share_key` (`account_id`, `share_id`),
  INDEX `share_connection_share_idx` (`share_id` ASC),
  INDEX `share_connection_account_idx` (`account_id` ASC),
  CONSTRAINT `recv_request_emigo`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recv_request_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recv_request_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `issued` INT(64) NOT NULL,
  `expires` INT(64) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `service_agent_emigo`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `service_agent_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `service_registry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `message` TEXT(65535) NOT NULL,
  `signature` VARCHAR(1024) NOT NULL,
  `issued` INT(64) NOT NULL,
  `expires` INT(64) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `user_agent_emigo`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reject_emigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reject_emigo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `emigo_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `reject_emigo_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reject_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reject_topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `topic_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `reject_topic_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `config_id` VARCHAR(32) NOT NULL,
  `str_value` VARCHAR(1024) NULL,
  `num_value` BIGINT(64) NULL,
  `bool_value` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `account_config_id_UNIQUE` (`account_id`, `config_id`),
  INDEX `account_idx` (`account_id` ASC),
  CONSTRAINT `account_config_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_alert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `alert_id` VARCHAR(32) NULL,
  `created` INT(64) NULL,
  `message` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `account_idx` (`account_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `account_alert_id_UNIQUE` (`account_id`, `alert_id`),
  CONSTRAINT `alert_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `attribute_id` VARCHAR(32) NOT NULL,
  `schema_id` VARCHAR(64) NOT NULL,
  `value` TEXT(65535) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `attribute_id_UNIQUE` (`account_id`, `attribute_id`),
  INDEX `account_attribute_account_idx` (`account_id` ASC),
  CONSTRAINT `account_attribute_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `label_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(1024)NULL,
  `logo` TEXT(65535) NULL,
  `description` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `label_id_UNIQUE` (`account_id`, `label_id`),
  INDEX `label_account_idx` (`account_id` ASC),
  CONSTRAINT `label_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emigo_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emigo_label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `label_idx` (`label_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `emigo_label_emigo_idx` (`emigo_id` ASC),
  CONSTRAINT `emigo_label_emigo`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emigo_label_label`
    FOREIGN KEY (`label_id`)
    REFERENCES `label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attribute_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attribute_label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_attribute_id` INT NULL,
  `label_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `attribute_idx` (`account_attribute_id` ASC),
  INDEX `label_idx` (`label_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `account_label_attribute`
    FOREIGN KEY (`account_attribute_id`)
    REFERENCES `account_attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_label_label`
    FOREIGN KEY (`label_id`)
    REFERENCES `label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `subject_id` VARCHAR(32) NOT NULL,
  `revision` INT NOT NULL,
  `created` INT(64) NOT NULL,
  `modified` INT(64) NOT NULL,
  `viewable` TINYINT NOT NULL,
  `restricted` TINYINT NOT NULL,
  `schema_id` VARCHAR(64) NOT NULL,
  `value` TEXT(65535) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `subject_id_UNIQUE` (`account_id`, `subject_id`),
  INDEX `subject_account_idx` (`account_id` ASC),
  CONSTRAINT `subject_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subject_asset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `asset_id` VARCHAR(32) NOT NULL,
  `ref_id` VARCHAR(32) NULL,
  `content_type` VARCHAR(64) NOT NULL,
  `asset_size` INT(64) NOT NULL,
  `asset_hash` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `subject_asset_id_UNIQUE` (`asset_id`, `subject_id`),
  INDEX `subject_asset_idx` (`subject_id` ASC),
  INDEX `asset_idx` (`asset_id` ASC),
  CONSTRAINT `asset_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subject_label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `subject_label_idx` (`subject_id` ASC),
  CONSTRAINT `subject_label_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_label_label`
    FOREIGN KEY (`label_id`)
    REFERENCES `label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
-- -----------------------------------------------------
-- Table `subject_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topic_subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `subject_topic_subject_idx` (`subject_id` ASC),
  INDEX `subject_topic_topic_idx` (`topic_id` ASC),
  CONSTRAINT `subject_topic_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_topic_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `pass` VARCHAR(64) NOT NULL,
  `issued` BIGINT(64) NULL,
  `expires` BIGINT(64) NULL,
  `account_show` TINYINT NOT NULL DEFAULT 0,
  `account_identity` TINYINT NOT NULL DEFAULT 0,
  `account_profile` TINYINT NOT NULL DEFAULT 0,
  `account_group` TINYINT NOT NULL DEFAULT 0,
  `account_share` TINYINT NOT NULL DEFAULT 0,
  `account_prompt` TINYINT NOT NULL DEFAULT 0,
  `account_app` TINYINT NOT NULL DEFAULT 0,
  `account_index` TINYINT NOT NULL DEFAULT 0,
  `account_catalog` TINYINT NOT NULL DEFAULT 0,
  `account_contact` TINYINT NOT NULL DEFAULT 0,
  `account_agent` TINYINT NOT NULL DEFAULT 0,
  `account_user` TINYINT NOT NULL DEFAULT 0,
  `account_access` TINYINT NOT NULL DEFAULT 0,
  `account_account` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pass_id_UNIQUE` (`account_id`, `pass`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC),
  CONSTRAINT `pass_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `hidden` TINYINT NOT NULL DEFAULT 0,
  `account_show` TINYINT NOT NULL DEFAULT 0,
  `account_identity` TINYINT NOT NULL DEFAULT 0,
  `account_profile` TINYINT NOT NULL DEFAULT 0,
  `account_group` TINYINT NOT NULL DEFAULT 0,
  `account_share` TINYINT NOT NULL DEFAULT 0,
  `account_prompt` TINYINT NOT NULL DEFAULT 0,
  `account_app` TINYINT NOT NULL DEFAULT 0,
  `account_index` TINYINT NOT NULL DEFAULT 0,
  `account_catalog` TINYINT NOT NULL DEFAULT 0,
  `account_agent` TINYINT NOT NULL DEFAULT 0,
  `account_user` TINYINT NOT NULL DEFAULT 0,
  `account_access` TINYINT NOT NULL DEFAULT 0,
  `account_account` TINYINT NOT NULL DEFAULT 0,
  `service_show` TINYINT NOT NULL DEFAULT 0,
  `service_identity` TINYINT NOT NULL DEFAULT 0,
  `service_profile` TINYINT NOT NULL DEFAULT 0,
  `service_group` TINYINT NOT NULL DEFAULT 0,
  `service_share` TINYINT NOT NULL DEFAULT 0,
  `service_prompt` TINYINT NOT NULL DEFAULT 0,
  `service_app` TINYINT NOT NULL DEFAULT 0,
  `service_index` TINYINT NOT NULL DEFAULT 0,
  `service_catalog` TINYINT NOT NULL DEFAULT 0,
  `service_agent` TINYINT NOT NULL DEFAULT 0,
  `service_user` TINYINT NOT NULL DEFAULT 0,
  `service_access` TINYINT NOT NULL DEFAULT 0,
  `service_account` TINYINT NOT NULL DEFAULT 0,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `tok_UNIQUE` (`token` ASC),
  INDEX `account_idx` (`account_id` ASC),
  INDEX `service_registry_idx` (`service_id` ASC),
  CONSTRAINT `service_service_registry`
    FOREIGN KEY (`service_id`)
    REFERENCES `service_registry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `service_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config_id` VARCHAR(32) NOT NULL,
  `str_value` VARCHAR(1024) NULL,
  `num_value` BIGINT(64) NULL,
  `bool_value` TINYINT NULL,
  UNIQUE INDEX `config_id_UNIQUE` (`config_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` INT(32) NOT NULL,
  `processor` INT NOT NULL,
  `memory` BIGINT(64) NOT NULL,
  `storage` BIGINT(64) NOT NULL,
  `requests` BIGINT(64) NOT NULL,
  `accounts` BIGINT(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `emigo_id` VARCHAR(64) NOT NULL,
  `account_token` VARCHAR(64) NOT NULL,
  `service_token` VARCHAR(64) NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE KEY `user_account_emigo_UNIQUE` (`account_id`, `emigo_id`),
  INDEX `service_account_idx` (`account_id` ASC),
  INDEX `user_emigo_idx` (`emigo_id` ASC),
  UNIQUE INDEX `service_token_UNIQUE` (`service_token` ASC),
  CONSTRAINT `user_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_emigo`
    FOREIGN KEY (`emigo_id`)
    REFERENCES `emigo_registry` (`emigo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL,
  `account_id` INT NOT NULL,
  `message` TEXT(65535) NOT NULL,
  `signature` VARCHAR(4096) NOT NULL,
  `pubkey` VARCHAR(4096) NOT NULL,
  `pubkey_type` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `account_message_emigo_UNIQUE` (`account_id` ASC),
  INDEX `account_message_account_idx` (`account_id` ASC),
  CONSTRAINT `account_message_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
