#!/bin/bash
export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR
md5sum -c upgrade.tar.md5
./upgrade

cd $CDIR
rm -rf $TMPDIR

exit 0

__ARCHIVE_BELOW__
