/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.coredb.api;

import org.coredb.model.AuthMessage;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "agent", description = "the agent API")
public interface AgentApi {

    @ApiOperation(value = "", nickname = "getAgentMessage", notes = "Generate authorization message for usage", response = AuthMessage.class, tags={ "agent", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = AuthMessage.class) })
    @RequestMapping(value = "/agent/service",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<AuthMessage> getAgentMessage(@NotNull @ApiParam(value = "share token with access", required = true) @Valid @RequestParam(value = "token", required = true) String token
);

}


