# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Build UI
      - name: React
        run: |
          cd ui
          npm install
          npm run-script build
          cd ..
          mkdir -p app/src/main/resources/static
          rm -rf app/src/main/resources/static/*
          mv ui/build/* app/src/main/resources/static/

      # Runs unit tests
      - name: Test
        run: |
          cd app
          mvn -B verify

      # Export installers
      - name: Export
        uses: actions/upload-artifact@v2
        with:
          name: coredb
          path: app/target/app.war 
